// <auto-generated />
using HotelManager.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelManager.API.Migrations
{
    [DbContext(typeof(HotelManagerDbContext))]
    partial class HotelManagerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HotelManager.API.Models.Countries.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kenya",
                            ShortName = "KE"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uganda",
                            ShortName = "UG"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tanzania",
                            ShortName = "TZ"
                        });
                });

            modelBuilder.Entity("HotelManager.API.Models.Hotels.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Western Kenya",
                            CountryId = 1,
                            Name = "Kenya One",
                            Rating = 5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Western UG",
                            CountryId = 2,
                            Name = "Uganda One",
                            Rating = 5
                        },
                        new
                        {
                            Id = 3,
                            Address = "Western TZ",
                            CountryId = 3,
                            Name = "TZ One",
                            Rating = 5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Nairobi Kenya",
                            CountryId = 1,
                            Name = "Kenya Two",
                            Rating = 5
                        });
                });

            modelBuilder.Entity("HotelManager.API.Models.Hotels.Hotel", b =>
                {
                    b.HasOne("HotelManager.API.Models.Countries.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelManager.API.Models.Countries.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
